### ISSUE TITLE
Extractor hood

### ISSUE THREAD

**Issue by arallsopp** [Mariusthvdb/custom-icons#22]
### Discussed in https://github.com/Mariusthvdb/custom-icons/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **Mariusthvdb** May 12, 2022</sup>
something that has always amazed is we don't have an icon for an extractor hood. My [request for that at Mdi](https://github.com/Templarian/MaterialDesign/issues/5738) was never followed up on, so Ill repeat it here ;-)

examples:

<img width="170" alt="103478023-56caeb80-4dc4-11eb-93c4-c06c820192fe" src="https://user-images.githubusercontent.com/33354141/168164042-7e1ab628-a0e5-43f3-8640-e2e00b3406e3.png">
<img width="195" alt="103478026-57fc1880-4dc4-11eb-83c1-833410aacc53" src="https://user-images.githubusercontent.com/33354141/168164048-bba9bcee-058d-40b4-9ae6-d23e847adbd3.png">
</div>

**Comment by arallsopp** [comment]
Here's one based on my hood. 24x24, 1px line weight (per hass-hue-icons)

<img width="515" alt="image" src="https://user-images.githubusercontent.com/2462104/168679288-1c4d8436-c763-4085-896b-e68bd6ab8506.png">

**Comment by arallsopp** [comment]
Here's the trapezoid version
<img width="646" alt="image" src="https://user-images.githubusercontent.com/2462104/168681693-bcd448b2-fb15-429d-ad79-95ad5233c37f.png">

**Comment by arallsopp** [comment]
| Icon | Name |
| :--- | :--- |
| ![hue:cooker-hood-trapezoid](https://raw.githubusercontent.com/Mariusthvdb/custom-icons/main/docs/svgs/cooker-hood-trapezoid.svg)| hue:cooker-hood-trapezoid|
| ![hue:cooker-hood-curve](https://raw.githubusercontent.com/Mariusthvdb/custom-icons/main/docs/svgs/cooker-hood-curve.svg)| hue:cooker-hood-curve|

**Comment by arallsopp** [comment]
I've closed this for now. I've used the [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons) standard line-weights of 1px against a 24px baseboard. If this library is targeting MDI standards, we probably need to re-draw and thicken those icons up a fair bit.  Looking at the readme page, this is apparent to me now.... :)

**Comment by Mariusthvdb** [comment]
Oeh, Nice!

if you add /change this to the repo, please do so via a Pr. That way the changes are auto generated in the next release…

thx!

**Comment by arallsopp** [comment]
Sorry. You're totally right. Last thing you need is someone dropping random files around :)

I've put the alt svg into https://github.com/Mariusthvdb/custom-icons/pull/23

I just exported from illustrator. I'll try to tweak inline with what you're saying above.

**Comment by arallsopp** [comment]
> That way the changes are auto generated in the next release…

Do you mean:

a: you have an action in place that reads the new file and builds the readme for you? 
or
b: you still have to build that lot, but the release notes get generated for you? 

If its `a`, you'll have to teach me that trick. I've not updated the script or readme in that PR, btw. Not sure of your process and don't want to scupper things. I'll change the json file, so that the helper sees the new icon, and leave it there for you to build as you see fit.

**Comment by Mariusthvdb** [comment]
no, I meant b.

Upon creating the new release, you can select 'auto-create release notes', and it simply lists all Pr's

btw, this new -alt icon, isnt listed in the overview yet, and is still using the width/height 24px. Is this un purpose? Why not add it as a 3d icon?

**Comment by arallsopp** [comment]
Ah. Not on purpose. Just late night :)
Feel free to tweak. 

I’ve updated the JSON to list it (I think) so on next helper load, get the json from the repo (via button) and it should update everything

**Comment by Mariusthvdb** [comment]
great I see it now yes.
omt: since there are no other cooker hoods icons available (as far as I have been able to establish) I feel we should at least call 1 of these plain `cooker-hood` . and have the others be variants of that?  what do you think? maybe set the new -alt vision as default without the suffix?

**Comment by arallsopp** [comment]
That's fine by me. I saw the icon request and tried to answer it. It's your repo and your library and any ideas you have about naming conventions automatically out rank mine.

In this instance, they're also better ideas by far :)

**Comment by SAOPP** [comment]
Hey guys! It's dope thanks, but, someone can help with adding cooker hood slider open icon? :smile: :+1: 

'Cuz I'm using dis shhh.. right now:

![image](https://user-images.githubusercontent.com/5647009/193894981-d33195c7-a9fc-493e-ab3f-4f4ca9d9d68c.png)

:laughing: 

Thanks in advance who can paint this :+1:

**Comment by SAOPP** [comment]
By the way, I just changed my icon from mdi to an icon from the pack today, and as you can see on the screen above, the icon of the cooker hood from the pack is dimmer against the background of the mdi and phu icons, is there a chance to get this icon more saturated, what do the mdi icons look like for example? 10x
