### ISSUE TITLE
Lutron Pico Icons

### ISSUE THREAD

**Issue by arallsopp** [Mariusthvdb/custom-icons#41]
Howdo.

I've had a [request](https://github.com/arallsopp/hass-hue-icons/issues/202) at [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons) for an icon for the Lutron Pico switch. Whilst I understand these are commonly paired with people's hue installs, they're not really a hue appliance, and I wondered whether you'd accept them here?

Here are the additions, which I've just created for [sdholden28](https://github.com/sdholden28). Would they be acceptable for custom-icons? 

| Icon | Name |
| :--- | :--- |
| ![lutron-pico](https://user-images.githubusercontent.com/2462104/192548718-6c138925-e56e-4f34-809b-249cd5425d73.svg) | lutron-pico |
| ![lutron-pico-b1](https://user-images.githubusercontent.com/2462104/192548700-1902ddde-f9ec-4f9e-89f7-0a15cd683c84.svg) | lutron-pico-b1 |
| ![lutron-pico-b2](https://user-images.githubusercontent.com/2462104/192548708-58c276fb-7599-4a4d-8c49-e64f2a7e2489.svg) | lutron-pico-b2 |
| ![lutron-pico-b3](https://user-images.githubusercontent.com/2462104/192548710-93f07eef-2625-4f77-96f5-21825b8f1e39.svg) | lutron-pico-b3 |
| ![lutron-pico-b4](https://user-images.githubusercontent.com/2462104/192548714-10e0baba-e1e2-40ef-b8e6-838880e4b9a3.svg) | lutron-pico-b4 |
| ![lutron-pico-b5](https://user-images.githubusercontent.com/2462104/192548716-346cbb90-6974-4d87-99dc-3ff7752a067b.svg) | lutron-pico-b5 |

**Comment by Mariusthvdb** [comment]
Sure and thanks!
Will you create the PR for it ?

Btw, I'd love to open a separate discussion on the format of admissible icons.

Don't want to wonder too far off from the MDI format.

Care to join in there please?

**Comment by arallsopp** [comment]
Sure. 

For the PR, is it just a case of adding the icons to the docs/svgs folder and letting you run your build scripts, or are there further actions. I can't remember how we set this up :)

**Comment by Mariusthvdb** [comment]
guess this can now be closed?
