### ISSUE TITLE
Hacs: repository structure not compliant

### ISSUE THREAD

**Issue by Mariusthvdb** [Mariusthvdb/custom-icons#5]
<img width="384" alt="Schermafbeelding 2022-05-12 om 17 30 11" src="https://user-images.githubusercontent.com/33354141/168112412-ff4090b2-9aff-43e9-9638-ac0b7fe32d27.png">

have to find what is blocking the repo to be admitted as custom repository in Hacs

**Comment by arallsopp** [comment]
Might be folders. There's a 

```
    "content_in_root": false
```
flag you can set. I use this so that I can have 'dist' vs 'docs'

**Comment by Mariusthvdb** [comment]
thx, but no, that doesnt help. Unless it might take a bit for the changes to be note by Hacs, I just tried and still the same error

**Comment by arallsopp** [comment]
I'll take a clone and see if I can get a similar output.

**Comment by Mariusthvdb** [comment]
no more need, its fixed, and I've dld it via Hacs meanwhile

**Comment by arallsopp** [comment]
Awesome. Well done, mate. It can be an arcane and dark art trying to get these things through :)
