### ISSUE TITLE
Dash cryptocurrency logo

### ISSUE THREAD

**Issue by lordbah** [Mariusthvdb/custom-icons#50]
How about adding the logo of Dash cryptocurrency?
https://media.dash.org/wp-content/uploads/dash-d-circle.svg

I was looking for it while adding Home Assistant widgets to track crypto prices.

**Comment by Mariusthvdb** [comment]
we dont use company icons, because of obvious legal issues.

You can drop it in your own folder if you use the CC however, at your own risk of course.

Please understand Ill close for the same reason
