### ISSUE TITLE
Icons not working in Labels

### ISSUE THREAD

**Issue by Revilo91** [Mariusthvdb/custom-icons#55]
Unfortunately, when trying to add an icon to the labels in Home Assistant (2024.5.0b0), this does not appear in the Gui

See here: Areas, labels & zones ->Labels 

Working here:
![image](https://github.com/Mariusthvdb/custom-icons/assets/39066472/1866021a-c9cf-464c-932c-70a352bc0268)
![image](https://github.com/Mariusthvdb/custom-icons/assets/39066472/49717c46-06a5-4b65-aa35-f030b69672f5)

---
See here: Devices & services -> Entities -> (Filters -> Labels)

Not working here:
![image](https://github.com/Mariusthvdb/custom-icons/assets/39066472/9f3a85b3-6927-423f-9fe9-315a45f0dbda)
![image](https://github.com/Mariusthvdb/custom-icons/assets/39066472/1deb5b06-039a-4c5a-b1c8-492f2d56b544)

**Comment by Mariusthvdb** [comment]
<img width="224" alt="Scherm­afbeelding 2024-04-26 om 12 30 10" src="https://github.com/Mariusthvdb/custom-icons/assets/33354141/53b9c5d3-0a04-456e-92d1-a43ad0733b56">

odd, Ive just tested this, and both the cli and the cil icons show up..

anything in the logs/inspector?

**Comment by Revilo91** [comment]
Very strange... While playing around with the languages, my instance of Home Assistant completely crashed and I even had to restart the VM. After that it seems to work.

--> “Have you ever turned it off and on again” is the motto


I'm closing this issue.


Sorry for the inconvenience.
